"""Modification longueur password

Revision ID: 1c2360a5686c
Revises: 6c605b06f63d
Create Date: 2024-09-25 15:16:44.153347

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1c2360a5686c"
down_revision = "6c605b06f63d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=mysql.VARCHAR(length=128),
            type_=sa.String(length=255),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.String(length=255),
            type_=mysql.VARCHAR(length=128),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
