"""Ajout des tables Rating et Comment

Revision ID: 6c605b06f63d
Revises: 568df31f8fc8
Create Date: 2024-09-25 14:22:06.698546

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "6c605b06f63d"
down_revision = "568df31f8fc8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("text", mysql.TEXT(), nullable=False),
        sa.Column("date", mysql.DATETIME(), nullable=False),
        sa.Column(
            "recipe_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipe.id"], name="comment_ibfk_1"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="comment_ibfk_2"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
