"""Ajout des clés étrangères dans RecipeIngredient

Revision ID: a4be082da104
Revises: 1c2360a5686c
Create Date: 2024-09-25 15:28:37.479213

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "a4be082da104"
down_revision = "1c2360a5686c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredient", schema=None) as batch_op:
        batch_op.alter_column(
            "name_ingredient",
            existing_type=mysql.VARCHAR(length=255),
            type_=sa.String(length=128),
            existing_nullable=False,
        )

    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.alter_column(
            "title",
            existing_type=mysql.VARCHAR(length=255),
            type_=sa.String(length=128),
            existing_nullable=False,
        )
        batch_op.alter_column("description", existing_type=mysql.TEXT(), nullable=True)
        batch_op.alter_column(
            "user_id", existing_type=mysql.INTEGER(display_width=11), nullable=True
        )
        batch_op.drop_column("image")

    with op.batch_alter_table("recipe_ingredient", schema=None) as batch_op:
        batch_op.alter_column("quantity", existing_type=mysql.FLOAT(), nullable=True)
        batch_op.alter_column(
            "unit",
            existing_type=mysql.VARCHAR(length=100),
            type_=sa.String(length=20),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_ingredient", schema=None) as batch_op:
        batch_op.alter_column(
            "unit",
            existing_type=sa.String(length=20),
            type_=mysql.VARCHAR(length=100),
            nullable=False,
        )
        batch_op.alter_column("quantity", existing_type=mysql.FLOAT(), nullable=False)

    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("image", mysql.VARCHAR(length=255), nullable=True)
        )
        batch_op.alter_column(
            "user_id", existing_type=mysql.INTEGER(display_width=11), nullable=False
        )
        batch_op.alter_column("description", existing_type=mysql.TEXT(), nullable=False)
        batch_op.alter_column(
            "title",
            existing_type=sa.String(length=128),
            type_=mysql.VARCHAR(length=255),
            existing_nullable=False,
        )

    with op.batch_alter_table("ingredient", schema=None) as batch_op:
        batch_op.alter_column(
            "name_ingredient",
            existing_type=sa.String(length=128),
            type_=mysql.VARCHAR(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
